# Exercícios NumPy

1. Faça _n_ = 200 e gere uma matriz *n X n* e dois vetores em $\mathbb{R}^n$, ambos com elementos inteiros fazendo:
    + A = np.floor(10\*rp.random.random((6,6))
    + b = np.sum(A,axis = 1)
    + z = np.ones((n,1))

In [2]:
import numpy as np

a. A solução exata de Ax = b deveria ser o vetor **z**. Por que? Explique. Pode-se calcular a solução usando numpy com o método solve do pacote linalg ou calculando $A^{-1}$ e então multiplicando $A^{-1}$ por __b__. Vamos comparar os dois métodos computacionais tanto para velocidade quanto para precisão. Pode-se usar o método *time()* do pacote time para medir o tempo decorrido em cada computação. Para isso use os comandos

In [24]:
n = 1000
A = np.floor(10*np.random.random((n,n)))
b = np.sum(A,axis = 1)
z = np.ones((n,1))

In [ ]:
A

In [ ]:
b

In [25]:
import time
inicio = time.time()
x = np.linalg.solve(A,b)
fim = time.time()
print(fim-inicio)
inicio = time.time()
y = np.linalg.inv(A).dot(b)
fim = time.time()
print(fim-inicio)

0.0678873062133789
0.09311056137084961


Que método é mais rápido?

Para comparar a precisão dos métodos podemos medir quão próximas as soluções **x** e __y__ estão da solução exata **z**. Faça isso com os comandos

In [26]:
print(np.max(np.abs(x-z)))
print(np.max(np.abs(y-z)))

1.7811307984061386e-12
4.254161467542872e-10


Que método produz a soulução mais precisa?

b. Repita a parte a usando n = 500 e n = 1000.

2. Faça A = np.floor(10\*np.random.random((6,6))). Por construção a matriz A terá elementos inteiros. Vamos mudar a sexta coluna de A de modo a tornar a matriz singular. Faça

In [27]:
A = np.floor(10*np.random.random((6,6)))
B = A.T
A[:,5] = -np.sum(B[0:5,:],axis=0)

a. Faça x = np.ones((6,1)) e calcule Ax. Como sabemos que A deve ser singular? Explique.

b. Faça B = x.dot(np.arange(1,7))
O produto AB deve ser igual à matriz nula. Por que? Explique. Verifique que isso é verdadeiro calculando AB com o método *dot*.

In [32]:
x = np.ones((6,1))

In [29]:
A.dot(x)

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [37]:
C = np.zeros((1,6))
C[0,:] = np.arange(1,7)
C

array([[1., 2., 3., 4., 5., 6.]])

In [38]:
B = x.dot(C)
B

array([[1., 2., 3., 4., 5., 6.],
       [1., 2., 3., 4., 5., 6.],
       [1., 2., 3., 4., 5., 6.],
       [1., 2., 3., 4., 5., 6.],
       [1., 2., 3., 4., 5., 6.],
       [1., 2., 3., 4., 5., 6.]])

In [39]:
A.dot(B)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])